---

- name: Install passlib library for ansible htpasswd module
  pip:
    name: passlib
    state: present

- debug: var=nginx_data

- name: Create nginx-proxy container with jwilder/nginx-proxy
  docker_container:
    name: nginx-proxy
    image: jwilder/nginx-proxy
    hostname: nginx-proxy
    published_ports: ['80:80', '443:443']
    restart_policy: always
    volumes:
    - '{{ nginx_data }}conf.d:/etc/nginx/conf.d'
    - '{{ nginx_data }}vhosts.d:/etc/nginx/vhost.d'
    - '{{ nginx_data }}certs:/etc/nginx/certs:ro'
    - '{{ nginx_data }}html:/usr/share/nginx/html:rw'
    - '{{ nginx_data }}htpasswd:/etc/nginx/htpasswd:ro'
    - /var/run/docker.sock:/tmp/docker.sock:ro
    labels: com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=nginx-letsencrypt

- name: Create nginx-letsencrypt container with jrcs/letsencrypt-nginx-proxy-companion
  docker_container:
    name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from: [nginx-proxy]
    restart_policy: always
    env:
      ACME_CA_URI: '{{ letsencrypt_uri }}'
    volumes:
    - '{{ nginx_data }}certs:/etc/nginx/certs:rw'
    - /var/run/docker.sock:/var/run/docker.sock:ro
