---

- name: Install role ?
  when: not ansible_facts.ansible_local[name]|default(false)
  include_role: name={{ name }}

- name: Prevent role from installing automatically next time
  include_role:
    name: setfact
  vars:
    key: '{{ name }}'
    value: 'installed'
    setfact_mode: 0755

- meta: flush_handlers
