---

- name: Migrate project database
  tags: [update, migrate]
  shell: |
    docker run --name {{ project_instance }}-migrate --rm \
    -v {{ project_media }}:/media -v {{ project_log }}:/log \
    {% for key, value in project_env.items() %}
    -e {{ key }}='{{ value | regex_replace("\'", "\\\'") }}' \
    {% endfor %}
    --network {{ project_instance }} \
    {{ image }} su uwsgi -c "django-admin migrate --noinput"
