stages:
- build
- test
- release

variables:
  IMAGE_TAG: ${CI_REGISTRY_IMAGE-hub.yourlabs.io/oss/playlabs}:$CI_COMMIT_SHA

build:
  stage: build
  image: tomkukral/buildah
  script:
  - buildah bud -t $IMAGE_TAG .
  - buildah push $IMAGE_TAG docker://$IMAGE_TAG

  before_script:
  - podman version
  - buildah version
  - podman login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
  
  after_script:
  - podman logout $CI_REGISTRY

py-qa:
  stage: build
  image: python:3-alpine
  before_script:
  - pip3 install flake8 mccabe
  script: >-
    flake8 
    --show-source
    --max-complexity=8
    --ignore=E305
    playlabs

alpine:
  stage: test
  image: $IMAGE_TAG
  script:
  - playlabs @localhost

arch:
  services: [retorillo/archlinux-sshd]
  stage: test
  image: $IMAGE_TAG
  script:
  - playlabs --nostrict -e ssh_norestart=1 root:root@archlinux-sshd

ubuntu:
  services: [rastasheep/ubuntu-sshd]
  stage: test
  image: $IMAGE_TAG
  script:
  - playlabs --nostrict -e ssh_norestart=1 root:root@ubuntu-sshd

pypi:
  stage: release
  image: $IMAGE_TAG
  only: [tags]
  script: |
    set -eux
    cd /app
    export PLAYLABS_VERSION="$CI_COMMIT_REF_NAME"
    pip3 install twine
    python3 setup.py sdist
    cat <<EOF > ~/.pypirc
    [pypi]
    username=yourlabs
    password=$PYPI_PASSWORD
    EOF
    twine upload dist/*
