stages:
- build
- test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
- podman version
- buildah version
- podman login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY

docker:
  stage: build
  image: tomkukral/buildah
  script:
    - echo $CI_REGISTRY
    - env
    - buildah bud -t $IMAGE_TAG .
    - buildah push docker://$IMAGE_TAG

test:
  stage: test
  image: hub.yourlabs.io/oss/playlabs:latest
  script:
    - playlabs @localhost
