stages:
- build
- test
- release

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  ANSIBLE_FORCE_COLOR: 'true'
  USER: gitlab

build:
  stage: build
  image: docker:stable
  services: ['docker:dind']
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
  - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
  - docker pull $CI_REGISTRY_IMAGE:master || true
  - docker build --cache-from $CI_REGISTRY_IMAGE:master -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
  after_script:
  - docker logout
# buildah version, better but where is caching support ?
#  image: tomkukral/buildah
#  before_script:
#  - podman login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
#  script:
#  - buildah bud -t $IMAGE_TAG .
#  - buildah push $IMAGE_TAG docker://$IMAGE_TAG
#  after_script:
#  - podman logout $CI_REGISTRY

py-qa:
  stage: build
  image: yourlabs/python
  script: flake8 --show-source --max-complexity=8 --ignore=E305 playlabs

py-test:
  stage: test
  image: $IMAGE_TAG
  script: py.test --cov playlabs

alpine:
  stage: test
  image: $IMAGE_TAG
  before_script: [ssh-keygen -f $HOME/.ssh/id_rsa]
  script:
  - playlabs @localhost

arch:
  services: [retorillo/archlinux-sshd]
  stage: test
  image: $IMAGE_TAG
  before_script: [ssh-keygen -f $HOME/.ssh/id_rsa]
  script:
  - playlabs --nostrict -e ssh_norestart=1 root:root@archlinux-sshd

ubuntu:
  services: [rastasheep/ubuntu-sshd]
  before_script: [ssh-keygen -f $HOME/.ssh/id_rsa]
  stage: test
  image: $IMAGE_TAG
  script:
  - playlabs --nostrict -e ssh_norestart=1 root:root@ubuntu-sshd

pypi:
  stage: release
  image: yourlabs/python
  only: [tags]
  script: |
    set -eux
    export PLAYLABS_VERSION="$CI_COMMIT_REF_NAME"
    pip3 install twine
    python3 setup.py sdist
    cat <<EOF > ~/.pypirc
    [pypi]
    username=yourlabs
    password=$PYPI_PASSWORD
    EOF
    twine upload dist/*
