stages:
- build
- test
- release

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build:
  stage: build
  image: docker:stable
  services: ['docker:dind']
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG

  before_script:
  - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin
  
  after_script:
  - docker logout

py-qa:
  stage: build
  image: yourlabs/python
  script: >-
    flake8 
    --show-source
    --max-complexity=8
    --ignore=E305
    playlabs

alpine:
  stage: test
  image: $IMAGE_TAG
  script:
  - ansible-playbook -v --user=None --limit localhost, --inventory localhost, --become --become-method sudo --become-user root -c local /app/playlabs/bootstrap.yml
  - playlabs @localhost

arch:
  services: [retorillo/archlinux-sshd]
  stage: test
  image: $IMAGE_TAG
  script:
  - playlabs --nostrict -e ssh_norestart=1 root:root@archlinux-sshd

ubuntu:
  services: [rastasheep/ubuntu-sshd]
  stage: test
  image: $IMAGE_TAG
  script:
  - playlabs --nostrict -e ssh_norestart=1 root:root@ubuntu-sshd

pypi:
  stage: release
  image: yourlabs/python
  only: [tags]
  script: |
    set -eux
    export PLAYLABS_VERSION="$CI_COMMIT_REF_NAME"
    pip3 install twine
    python3 setup.py sdist
    cat <<EOF > ~/.pypirc
    [pypi]
    username=yourlabs
    password=$PYPI_PASSWORD
    EOF
    twine upload dist/*
