---

- name: /etc/systemd/system/docker.service.d
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
#
# - name: /etc/systemd/system/docker.service.d/override.conf
#   copy:
#     dest: /etc/systemd/system/docker.service.d/override.conf
#     content: |
#       [Service]
#       ExecStart=
#       ExecStart=/usr/bin/dockerd -H fd:// --iptables=false --ip-masq=false

- name: Install apt-transport-https
  when: ansible_os_family == 'Debian'
  apt:
    name:
    - apt-transport-https
    - gpg
    update_cache: yes
    cache_valid_time: 3600

- name: Install docker repository key
  when: ansible_os_family == 'Debian'
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install docker repository
  when: ansible_os_family == 'Debian'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} edge
    state: present

- name: Update apt
  when: ansible_os_family == 'Debian'
  apt:
    update_cache: yes

- name: Install docker-ce
  package:
    name: '{{ "docker-ce" if ansible_os_family == "Debian" else "docker" }}'
    state: present

- name: Ensure python-docker is uninstalled, we'll need the pip module
  package:
    name: python-docker
    state: absent

- name: Install pip for docker pip module
  package:
    name: '{{ pip_package_name[ansible_os_family] }}'
    state: present

- name: Pip install docker
  pip:
    name: docker
    state: present

- name: Start docker on boot
  service:
    name: docker
    enabled: yes
    state: started

- name: Add active_users to docker group
  with_items: '{{ users|default([]) }}'
  user:
    name: '{{ item["name"] }}'
    state: present
    groups: docker
    append: yes

- name: Increase vm.max_map_count to 1048576
  sysctl:
    name: vm.max_map_count
    value: 1048576
    state: present
