---
- name: Setup
  include_role:
    name: roleonce
  vars:
    name: nginx

- name: Create configuration directories
  file:
    state: directory
    path: /etc/netdata

- name: Upload configuration
  with_filetree: roles/netdata/templates
  when: item.state == 'file'
  template:
    src: '{{ item.path }}'
    dest: '/etc/netdata/{{ item.path }}'

- name: Install dependencies
  apt:
    name: '{{ netdata_packages }}'
    state: present
  when: ansible_os_family == "Debian"

- name: enable sysfs KSM
  lineinfile:
    path: /etc/sysfs.conf
    line: 'kernel/mm/ksm/run = 1'

- name: config sysfs KSM
  lineinfile:
    path: /etc/sysfs.conf
    line: 'kernel/mm/ksm/sleep_millisecs = 1000'

- name: Clone repo
  register: netdata_git
  git:
    clone: yes
    update: yes
    repo: https://github.com/firehol/netdata.git
    dest: /usr/src/netdata

- name: Install script
  when: netdata_git.changed
  shell: cd /usr/src/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here

- name: Make netdata-proxy home
  file: name=/home/netdata-proxy state=directory

- name: Install nginx proxy config
  copy:
    dest: /home/netdata-proxy/nginx.conf
    content: |
      server {
        listen 80;
        location / {
          proxy_pass http://172.17.0.1:19999;

          proxy_redirect off;
          proxy_http_version 1.1;

          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }

- name: Setup nginx proxy container
  tags: docker
  docker_container:
    name: netdata-proxy
    image: nginx
    restart_policy: unless-stopped
    volumes:
    - /home/netdata-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    env:
      LETSENCRYPT_EMAIL: '{% if letsencrypt_email %}{{ letsencrypt_email }}{% endif %}'
      LETSENCRYPT_HOST: '{% if letsencrypt_email %}{{ netdata_dns }}{% endif %}'
      VIRTUAL_HOST: '{{ netdata_dns }}'

- name: Make prometheus home
  file: name=/home/prometheus state=directory

- name: Copy prometheus configuration
  copy:
    src: files/prometheus.yml
    dest: /home/prometheus/prometheus.yml

- name: Setup prometheus container
  tags: docker
  docker_container:
    hostname: prometheus
    name: prometheus
    image: prom/prometheus
    restart_policy: unless-stopped
    volumes:
    - /home/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    ports:
    - 9090:9090
    env:
      VIRTUAL_HOST: '{{ prometheus_dns }}'

- name: Make grafana home
  file: name=/home/grafana state=directory

- name: Make grafana datasources dir
  file: name=/home/grafana/datasources state=directory

- name: Setup grafana container
  tags: docker
  docker_container:
    name: grafana
    image: grafana/grafana
    restart_policy: unless-stopped
    hostname: grafana
    volumes:
    - grafana-data:/var/lib/grafana
    - grafana-plugins:/var/lib/grafana/plugins
    ports:
    - 3000:3000
    env:
      VIRTUAL_HOST: '{{ grafana_dns }}'
      GF_SECURITY_ADMIN_PASSWORD: '{{ grafana_password }}'

- name: Install netdata htaccess
  vars:
    htaccess_dns: '{{ netdata_dns }}'
    htaccess_service: netdata
  include_role:
    name: nginx_htpasswd
