---

- name: Install pip for openshift pip module required for k8s_raw ansible module
  delegate_to: localhost
  package:
    name: python-pip
    state: present

- name: Pip install openshift
  delegate_to: localhost
  pip:
    name: openshift
    state: present

- name: Install users
  include: users.yml
  when: '"k8s" in user.get("roles", [])'
  loop: '{{ users }}'
  loop_control:
    loop_var: user

- name: Install namespaces
  with_dict: '{{ k8s_namespaces }}'
  delegate_to: localhost
  k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: '{{ item.key }}'
