---
letsencrypt_email:

netdata_home: /home/netdata
netdata_email_sender: netdata@localhost

netdata_packages:
- autoconf
- autoconf-archive
- autogen
- automake
- gcc
- git
- libmnl-dev
- make
- pkg-config
- uuid-dev
- zlib1g-dev
