---
# Use this playbook first to install python (for ansible) and setup your user
# (username: $USER) and RSA key ($HOME/.ssh/id_rsa.pub) when you have already a
# user + sudo ssh access.
#
# Once this playbook executed with success, check that you can connect with
# $USER@host and do `sudo -s` without being prompted by a password.
#
# Then you can use other playbooks such as ssh.yml to clean the SSH
# configuration and create other users.
#
# Example to bootstrap an arch linux server from Online.net:
#
#   ansible-playbook --ask-sudo-pass --become --become-user=root --become-method=sudo -i inventories/yourlabs/inventory -v playbooks/bootstrap/arch-sudo.yml
#

- hosts: all

  # Don't crash if python isn't installed, we'll install it
  gather_facts: False

  tasks:
  - name: Cancel now if /etc/playlabs/initialized exists unless force=true
    when: force|default(false) == false
    raw: ls /etc/playlabs/initialized
    register: initialized
    failed_when: initialized.rc == 0
    changed_when: false

  - name: Raw bootstrap.sh
    script: 'init.sh'
    register: out
    changed_when: "'+ exit 0' not in out.stdout_lines"

- hosts: all
  tasks:
  - name: Install packages to add user
    package: name={{ item }}
    async: 45
    poll: 0
    with_items:
    - '{{ "shadow" if ansible_os_family == "Alpine" else "passwd" }}'
    - sudo

  - name: Create sudo group
    group:
      name: sudo
      state: present

  - name: Install your user account
    with_items:
    - root
    - '{{ lookup("env", "USER") }}'
    user:
      name: '{{ item }}'
      state: present
      shell: /bin/bash
      groups: sudo

  - name: Install your ssh key
    async: 45
    poll: 0
    authorized_key:
      user: '{{ lookup("env", "USER") }}'
      state: present
      key: '{{ lookup("file", lookup("env", "HOME") + "/.ssh/id_rsa.pub") }}'

  - name: Passwordless sudo for sudo group
    lineinfile:
      path: /etc/sudoers.d/passwordless
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      create: yes
      owner: root
      group: root
      mode: 0600

  - name: Create /etc/playlabs, let's store grains lol
    file:
      path: /etc/playlabs
      owner: root
      mode: 700
      state: directory

  - name: Write init file
    copy:
      content: Initialized by {{ lookup("env", "USER") }} lookup('pipe', 'date  +\"%Y%m%d\"')
      dest: /etc/playlabs/initialized
