---

- name: Install htaccess
  with_items: '{{ users }}'
  tags: users
  when: >-
    item.name|vaulted_password(false)
    and (
        'superuser' in item.get('roles', {}).get(htaccess_service, [])
        or htaccess_service in item.get('roles', {}).get('superuser', {})
    )
  htpasswd:
    path: '{{ nginx_home }}/htpasswd/{{ htaccess_dns }}'
    name: '{{ item.name }}'
    password: '{{ item.name|vaulted_password() }}'
    owner: 101
    group: 101
    mode: 0600
