---

- name: Update docker-image
  tags: update,docker-run
  copy:
    content: '{{ project_image }}'
    dest: '{{ project_home }}/docker-image'
    mode: 0700
    owner: '{{ deploy_user|default("root") }}'
    unsafe_writes: true

- name: Update docker-run.sh
  tags: docker-run
  template:
    src: docker-run.sh
    dest: '{{ project_home }}/docker-run.sh'
    mode: 0700
    owner: root

- name: Execute docker-run.sh
  tags: update, docker-run
  shell: sudo {{ project_home }}/docker-run.sh
