---
- name: Update docker-run.sh
  tags: update, docker-run
  copy:
    dest: '{{ project_home }}/docker-run.sh'
    mode: 0744
    content: |
      #!/bin/bash -eux
      docker rm -f {{ project_instance }} || echo could not rm container
      docker run -d --name {{ project_instance }} --restart unless-stopped \
          {% for plugin in project_plugins -%}
          {%- for option in hostvars[inventory_hostname].get('project_' + plugin + '_docker_options', []) %}
          {{ option }} \
          {% endfor %}
          {% endfor -%}
          -v {{ project_log_home }}:{{ project_log_mount }} \
          {% for key, value in project_env.items() %}
          -e {{ key }}='{% if value.replace is defined %}{{ value.replace("'", "\\'") }}{% else %}{{ value }}{% endif %}' \
          {% endfor %}
          {{ project_image }}
      docker network connect {{ project_instance }} {{ project_instance }}
      {% for network in project_networks %}
      docker network connect {{ network }} {{ project_instance }}
      {% endfor %}

- name: Execute docker-run.sh
  tags: update, docker-run
  shell: bash -eux {{ project_home }}/docker-run.sh
