---
- name: Update docker-run.sh
  tags: update, docker-run
  template:
    src: docker-run.sh
    dest: '{{ project_home }}/docker-run.sh'
    mode: 0700
    user: '{{ deploy_user|default("root") }}'

- name: Execute docker-run.sh
  tags: update, docker-run
  shell: sudo {{ project_home }}/docker-run.sh
