---

- name: Install htaccess
  when: project_htaccess
  tags: users
  vars:
    htaccess_dns: '{{ project_dns }}'
    htaccess_service: '{{ project_instance }}'
  include_role:
    name: nginx_htpasswd

# not that fast: wait for actual use case to enable
# - name: Get custom nginx configuration from the image if any
#   shell: '{{ project_exec }} bash -c "test ! -f /app/etc/nginx.conf || cat /app/etc/nginx.conf"'
#   register: project_nginx_config

- name: Configure nginx
  copy:
    dest: '{{ nginx_home|default("/home/nginx/") }}vhosts.d/{{ project_dns }}'
    content: |
      client_max_body_size 10M;
      client_body_buffer_size 10M;
      uwsgi_buffering off;

- name: Configure nginx for redirects
  with_items: '{{ project_dns_redirect }}'
  copy:
    dest: '{{ nginx_home|default("/home/nginx/") }}vhosts.d/{{ item }}_location'
    content: rewrite ^/(.*) https://{{ project_dns }}/$1 permanent;
