---

- name: Install htaccess
  when: project_htaccess
  tags: users
  vars:
    htaccess_dns: '{{ project_dns }}'
    htaccess_service: '{{ project_instance }}'
  include_role:
    name: nginx_htpasswd

- name: Configure nginx
  copy:
    dest: '{{ nginx_home|default("/home/nginx/") }}vhosts.d/{{ project_dns }}'
    content: |
      client_max_body_size 10M;
      client_body_buffer_size 10M;
      {% if 'STATIC_URL' in project_image_env %}
      location {{ project_image_env['STATIC_URL'] }} {{ '{' }}
        gzip on;
        {% if 'STATIC_EXPIRES' in project_image_env %}
        expires {{ project_image_env['STATIC_EXPIRES'] }};
        {% endif %}
      {{ '}' }}
      {% endif %}

- name: Configure nginx for redirects
  with_items: '{{ project_dns_redirect }}'
  copy:
    dest: '{{ nginx_home|default("/home/nginx/") }}vhosts.d/{{ item }}_location'
    content: rewrite ^/(.*) https://{{ project_dns }}/$1 permanent;
