---

- name: Pull project image
  tags: update
  docker_image:
    name: '{{ project_image }}'
    force: yes

- name: Docker inspect image
  docker_image_facts:
    name: '{{ project_image }}'
  register: project_image_facts

- set_fact: 
    project_image_env: "{{ project_image_facts['images'][0]['Config']['Env']|docker_env_dict }}"
 
- set_fact:
    project_plugins: "{{ project_image_env.get('PLAYLABS_PLUGINS', '').split(',') }}"
  when: project_plugins == []

- include: vars.yml
  tags: update
- include: deploy.yml
- include: home.yml
- include: http.yml
- include: backup.yml
- include: logrotate.yml

- name: Create project network
  docker_network:
    name: '{{ project_instance }}'

- name: Stop container if any
  failed_when: false
  tags: stop
  docker_container:
    name: '{{ project_instance }}'
    state: stopped

- name: Execute backup
  when: project_backup_password != False
  tags: [update, migrate, backup]
  shell: sudo {{ project_home }}/backup.sh

- name: Running deploy.pre.yml for plugins
  with_items: '{{ project_plugins }}'
  include: plugins/{{ item }}/deploy.pre.yml
  tags: predeploy

- include: docker.yml
  tags: deploy

- name: Running deploy.post.yml for plugins
  with_items: '{{ project_plugins }}'
  include: plugins/{{ item }}/deploy.post.yml
  tags: postdeploy

- block:
  - name: Verify URL
    register: url_verify
    tags: check
    get_url:
      url: '{{ "https" if project_letsencrypt_email else "http" }}://{{ project_dns }}'
      validate_certs: '{{ "yes" if project_letsencrypt_environment == "production" else "no" }}'
      dest: /dev/null
  always:
  - shell: docker logs {{ project_instance }} | tail -n 100
    tags: check
    changed_when: false
