---
project:
  dns: '{{ dns }}'
project_plughins: '{{ hostvars[inventory_hostname].get(project_prefix + "_" + instance|default("staging") + "_hooks", hooks.split(",") if hooks is defined else []) }}'
