---
# This file serves as tutorial to use secrets. In this inventory directory, you
# need to create a file with name .vault with content "foo" as such:
#
#   echo foo -n > .vault
#
# Do **not** add it to the repository.
#
# Now encrypt the backup_password variable below:
#
#   $ echo -n your backup password | ansible-vault --vault-id .vault encrypt_string --name backup_password > group_vars/all/backup_password.yml
#
# Note that you can invoke this variable in cleartext variables files, because
# of Ansible's lazy evaluation of variable value.
#
# In the same fashion of gpg, this can support multiple passwords for encryption,
# make sure that you read teh official documentation
# https://docs.ansible.com/ansible/latest/user_guide/vault.html#providing-vault-passwords
#
# Note for old people: this method is NOT compatible with the
# ANSIBLE_VAULT_PASSWORD_FILE method which is DEPRECATED !!
