---
# This is the reason why you want CI on your inventory script: to auto-update
# user accounts with `playlabs install ssh`, every time a change to this file
# is pushed.

users:
- name: hacker
  email: hacker1337@example.pcom
  roles:
    netdata: [sysadmin, domainadmin, dba, webmaster, proxyadmin]
    superuser: [sentry, project-staging]
    ssh: [sudo]
    # To generate your own crypted password run this command:
    # $ echo -n your vault password > .vault
    # $ ansible-vault --vault-id .vault encrypt_string 'mypassword'

# The example inventory provides one deploy user, than has no sudo
# access, but can call the backup script in all services. His ssh
# key is automatically picked up in keys/deploy because playlabs looks
# for keys/$USER. For deploy user, we have a key without password, that
# is supposed to be crypted with ansible-vault before commit:
#
# $ ssh-keygen -t ed25519 -a 100
# $ echo -n your vault password > .vault
# $ ansible-vault encrypt --vault-id .vault keys/deploy
- name: deploy
  sudo: 'ALL=(ALL) NOPASSWD: /home/*/backup.sh'
