---

- name: Set ssh service name for Arch
  when: ansible_os_family in ('Archlinux', 'RedHat')
  set_fact:
    ssh_service_name: sshd

- name: Set ssh service name for Debian
  when: ansible_os_family == 'Debian'
  set_fact:
    ssh_service_name: ssh

- name: Install users group
  group:
    name: users
    state: present

- name: Install users
  with_items: '{{ users }}'
  user:
    name: '{{ item["name"] }}'
    state: present
    shell: /bin/bash
    groups: '{% if "ssh" in item.get("roles", {}) %}{{ ",".join(item["roles"]["ssh"]) }},{% endif %}users'
    append: yes

- name: Install ssh public keys
  with_items: '{{ users }}'
  when: item['name']|key_pub_exists
  authorized_key:
    user: '{{ item["name"] }}'
    state: present
    key: '{{ item["name"]|key_pub_read }}'

- name: Find sshd configuration
  stat: path=/etc/ssh/sshd_config
  register: sshd_config

- name: Update sshd configuration
  notify: Restart sshd
  when: sshd_config.stat.exists
  with_dict: '{{ sshd_options }}'
  lineinfile:
    path: /etc/ssh/sshd_config
    line: '{{ item.key }} {{ item.value }}'
    regexp: '^#?{{ item.key }}'
    backup: yes
