---

- name: Install users
  loop: '{{ users }}'
  loop_control:
    loop_var: user
  when: user['name']|key_pub_exists
  include_tasks: user.yml

- name: Install local user
  user:
    name: '{{ lookup("env", "USER") }}'
    state: present
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Unlock local user
  shell: usermod -p '*' {{ lookup('env', 'USER') }}
 
- name: Install your ssh key on your user and root
  authorized_key:
    user: '{{ lookup("env", "USER") }}'
    state: present
    key: '{{ lookup("file", item) }}'
  with_fileglob:
  - '{{ lookup("env", "HOME") + "/.ssh/id_*.pub" }}'

- name: Remove users to remove
  with_items: '{{ users_remove|default([]) }}'
  user:
    name: '{{ item }}'
    state: absent

