---
- name: Dependency roles
  include_role:
    name: roleonce
  vars:
    name: docker

- include: setup.yml

- name: Install users
  include: users.yml

- name: Install namespaces
  include: namespaces.yml
