---

passbolt_data: /home/passbolt/
passbolt_backup: '{{ passbolt_data }}backup/'
passbolt_config_source: '{{ passbolt_data }}config/'
passbolt_config_dest: /var/www/passbolt/config
nginx_data: /home/nginx/
